#Codigo adaptado em MySQL

#MySQL usa AUTO_INCREMENT em vez de AUTOINCREMENT.
Tipo de dado DOUBLE: Em MySQL, você pode usar DECIMAL para valores monetários.

CREATE TABLE TIPO_PRODUTO (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE TIPO_PAGTO (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUTOS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(50) NOT NULL,
  VALOR DECIMAL(10, 2) NOT NULL,
  ID_TIPO_PRODUTO INT NOT NULL,
  FOREIGN KEY (ID_TIPO_PRODUTO) REFERENCES TIPO_PRODUTO(ID)
);

CREATE TABLE PEDIDOS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DATA DATETIME NOT NULL,
  ID_TIPO_PAGTO INT NOT NULL,
  VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (ID_TIPO_PAGTO) REFERENCES TIPO_PAGTO(ID)
);

CREATE TABLE PEDIDOS_PRODUTOS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ID_PEDIDO INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  QTDE INT NOT NULL,
  VALOR_UNIT DECIMAL(10, 2) NOT NULL,
  VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
);
